language: node_js

node_js:
  - "8"

sudo: required
services:
    - docker

before_install:
    - docker build -f Dockerfile.dev -t savani78/react-docker .

script:
    - docker run savani78/react-docker npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    access_key_id: 
        secure: "$AWS_ACCESS_KEY"
    secret_access_key: 
        secure: "$AWS_SECRET_KEY"
    region: "us-east-1"
    app: "docker-test"
    env: "DockerTest-env"
    bucket_name: "elasticbeanstalk-us-east-1-537677756342"
    bucket_path: "docker-test"
    on:
        branch: master
